[Variables]
; CPU Temperature
HWiNFO_CpuEnhancedSensorId=0xf0000501
HWiNFO_CpuEnhancedSensorInstance=0x0
HWiNFO_CpuTemp=0x1000000

; CPU Usage
HWiNFO_CpuSensorId=0xf0000300
HWiNFO_CpuSensorInstance=0x0
HWiNFO_CpuUsage=0x7000043

; RAM
HWiNFO_SystemSensorId=0xf0000301
HWiNFO_SystemSensorInstance=0x0
HWiNFO_MemoryUsed=0x8000003
HWiNFO_MemoryFree=0x8000004

; GPU Temperature
HWiNFO_GpuSensorId=0xe0002000
HWiNFO_GpuSensorInstance=0x0
HWiNFO_GpuTemp=0x1000000

; GPU Usage
HWiNFO_GpuUsage=0x7000000

; VRAM
HWiNFO_GpuMemoryUsed=0x80000fc
HWiNFO_GpuMemoryFree=0x80000fb
